# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cy2xffOD9_fR8Gc05pK4q2ZevCC5GwII
"""

import joblib
import os
import numpy as np

def predict_sales(steps=10):
    # Cari path model relatif terhadap file ini
    base_dir = os.path.dirname(os.path.abspath(__file__))
    model_path = os.path.join(base_dir, "sarima_model.pkl")

    model = joblib.load(model_path)
    forecast = model.forecast(steps=steps)
    return forecast

if __name__ == "__main__":
    preds = predict_sales(steps=20)
    print("Prediksi penjualan mobil 20 minggu ke depan:")
    print(preds)